2022-09-09 18:51:51,113 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 18:51:55,575 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'module' object is not callable"), <traceback object at 0x000001BDD348F2C0>)
2022-09-09 18:52:15,351 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 18:52:31,254 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'module' object is not callable"), <traceback object at 0x000001D023DE76C0>)
2022-09-09 18:52:39,058 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:00:34,457 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:00:34,459 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'module' object is not callable"), <traceback object at 0x0000020AB6F11CC0>)
2022-09-09 19:00:55,003 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:01:02,491 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('time.time() takes no keyword arguments'), <traceback object at 0x00000272F0B32140>)
2022-09-09 19:01:40,395 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:01:40,398 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'module' object is not callable"), <traceback object at 0x0000017556731EC0>)
2022-09-09 19:07:00,007 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:07:00,013 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x000001CB852A1F40>)
2022-09-09 19:08:06,933 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:08:06,936 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x00000258F2651D80>)
2022-09-09 19:08:51,533 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:08:51,536 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x00000113EA701A00>)
2022-09-09 19:09:03,621 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:09:03,624 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x0000021406EA1D80>)
2022-09-09 19:09:35,057 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:09:35,059 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x0000023E12382000>)
2022-09-09 19:10:40,514 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:10:40,517 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError('unbound method datetime.time() needs an argument'), <traceback object at 0x000001A8D0295C40>)
2022-09-09 19:12:16,541 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:13:07,971 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:14:12,532 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'module' object is not callable"), <traceback object at 0x000001CDBC137100>)
2022-09-09 19:14:32,786 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:15:44,151 - GivTCP_Write_1 - [CRITICAL] - Mode result is:None
2022-09-09 19:15:45,159 - GivTCP_Write_1 - [ERROR] - Setting Discharge Rate failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x0000017E8D8248C0>)
2022-09-09 19:15:45,162 - GivTCP_Write_1 - [CRITICAL] - DischargeRate result is:{"result": "Setting Discharge Rate failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x0000017E8D8248C0>)"}
2022-09-09 19:17:53,615 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:35:15,115 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:35:15,122 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(1900, 1, 1, 16, 0), datetime.datetime(1900, 1, 1, 7, 0)) - (datetime.datetime(2022, 9, 9, 19, 35, 15, 122040), datetime.datetime(2022, 9, 9, 19, 50, 15, 122040))
2022-09-09 19:35:51,552 - GivTCP_Write_1 - [CRITICAL] - Mode result is:None
2022-09-09 19:35:52,568 - GivTCP_Write_1 - [ERROR] - Setting Discharge Rate failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x0000013575B7F140>)
2022-09-09 19:37:30,242 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:37:30,248 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(1900, 1, 1, 16, 0), datetime.datetime(1900, 1, 1, 7, 0)) - (datetime.datetime(2022, 9, 9, 19, 37, 30, 248458), datetime.datetime(2022, 9, 9, 19, 52, 30, 248458))
2022-09-09 19:37:44,639 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 44 bytes (0 received)'), <traceback object at 0x0000027E59B21D00>)
2022-09-09 19:38:18,767 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:38:18,774 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(1900, 1, 1, 16, 0), datetime.datetime(1900, 1, 1, 7, 0)) - (datetime.datetime(2022, 9, 9, 19, 38, 18, 774270), datetime.datetime(2022, 9, 9, 19, 53, 18, 774270))
2022-09-09 19:39:53,359 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:39:53,365 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(1900, 1, 1, 16, 0), datetime.datetime(1900, 1, 1, 7, 0)) - (datetime.datetime(2022, 9, 9, 19, 39, 53, 365891), datetime.datetime(2022, 9, 9, 19, 54, 53, 365891))
2022-09-09 19:39:59,551 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("GivEnergyClient.set_mode_storage() got multiple values for argument 'export'"), <traceback object at 0x0000015372F07F40>)
2022-09-09 19:41:41,702 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:41:41,709 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(1900, 1, 1, 16, 0), datetime.datetime(1900, 1, 1, 7, 0)) - (datetime.datetime(2022, 9, 9, 19, 41, 41, 709146), datetime.datetime(2022, 9, 9, 19, 56, 41, 709146))
2022-09-09 19:42:26,206 - GivTCP_Write_1 - [CRITICAL] - Mode result is:None
2022-09-09 19:47:49,833 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:47:49,839 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'AttributeError'>, AttributeError("attribute 'hour' of 'datetime.datetime' objects is not writable"), <traceback object at 0x000001C810A02180>)
2022-09-09 19:48:42,274 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:48:42,282 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'datetime.datetime' object is not callable"), <traceback object at 0x0000021C13C7BF40>)
2022-09-09 19:49:03,181 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:49:10,555 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'TypeError'>, TypeError("'datetime.datetime' object is not callable"), <traceback object at 0x0000019AFB32C280>)
2022-09-09 19:51:52,119 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:52:01,530 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(2022, 9, 9, 19, 51, 55, 42318), datetime.datetime(2022, 9, 9, 19, 51, 56, 655452)) - (datetime.datetime(2022, 9, 9, 19, 52, 1, 530584), datetime.datetime(2022, 9, 9, 20, 7, 1, 530584))
2022-09-09 19:54:18,840 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x000001B87F378400>)
2022-09-09 19:54:26,930 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:54:30,472 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(2022, 9, 9, 19, 54, 29, 333848), datetime.datetime(2022, 9, 9, 19, 54, 30, 472015)) - (datetime.datetime(2022, 9, 9, 19, 54, 30, 472015), datetime.datetime(2022, 9, 9, 20, 9, 30, 472015))
2022-09-09 19:54:34,952 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x0000025ACFDE2540>)
2022-09-09 19:59:18,838 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 19:59:32,935 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'ValueError'>, ValueError("invalid literal for int() with base 10: '16:'"), <traceback object at 0x0000027833404D00>)
2022-09-09 19:59:59,931 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:01:23,979 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:01:46,010 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:02:09,654 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot to: (datetime.datetime(2022, 9, 9, 16, 0, 47, 931772), datetime.datetime(2022, 9, 9, 7, 0, 48, 935508)) - (datetime.datetime(2022, 9, 9, 20, 2, 2, 582886), datetime.datetime(2022, 9, 9, 20, 17, 2, 582886))
2022-09-09 20:02:15,963 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x000001E3D23DD100>)
2022-09-09 20:04:14,172 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:04:14,179 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot: (datetime.datetime(2022, 9, 9, 16, 0, 14, 175620), datetime.datetime(2022, 9, 9, 7, 0, 14, 175620)) -> (datetime.datetime(2022, 9, 9, 20, 4, 14, 179621), datetime.datetime(2022, 9, 9, 20, 19, 14, 179621))
2022-09-09 20:04:15,375 - GivTCP_Write_1 - [CRITICAL] - Mode result is:None
2022-09-09 20:06:57,471 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:06:57,473 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot: (datetime.datetime(2022, 9, 9, 20, 6, 57, 473048), datetime.datetime(2022, 9, 9, 20, 21, 57, 473048))
2022-09-09 20:06:58,866 - GivTCP_Write_1 - [CRITICAL] - Mode result is:None
2022-09-09 20:07:03,481 - GivTCP_Write_1 - [CRITICAL] - DischargeRate result is:{"result": "Setting Discharge Rate was a success"}
2022-09-09 20:07:03,482 - GivTCP_Write_1 - [ERROR] - Force Export failed: (<class 'ValueError'>, ValueError('Functions from the __main__ module cannot be processed by workers'), <traceback object at 0x0000023048721EC0>)
2022-09-09 20:12:55,752 - GivTCP_Write_1 - [CRITICAL] - Forcing Export for 15 minutes
2022-09-09 20:12:55,764 - GivTCP_Write_1 - [CRITICAL] - Setting timeslot: 20:12 => 20:27
2022-09-09 21:38:34,076 - GivTCP_Write_1 - [CRITICAL] - Forcing Charge for 2 minutes
2022-09-09 21:38:34,643 - GivTCP_Write_1 - [ERROR] - Force charge failed: (<class 'TypeError'>, TypeError('can only concatenate str (not "int") to str'), <traceback object at 0x0000025598CCD900>)
2022-09-09 21:38:43,888 - GivTCP_Write_1 - [CRITICAL] - Forcing Charge for 2 minutes
2022-09-09 21:39:39,767 - GivTCP_Write_1 - [ERROR] - Setting Charge Enable failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x000001FB8D767B00>)
2022-09-09 21:40:33,240 - GivTCP_Write_1 - [ERROR] - Force charge failed: (<class 'TypeError'>, TypeError('can only concatenate str (not "int") to str'), <traceback object at 0x000001FB8D6F3900>)
2022-09-09 21:41:00,462 - GivTCP_Write_1 - [CRITICAL] - Forcing Charge for 2 minutes
2022-09-09 21:41:38,972 - GivTCP_Write_1 - [CRITICAL] - Forcing Charge for 2 minutes
2022-09-09 21:41:41,520 - GivTCP_Write_1 - [CRITICAL] - Setting target SOC to: 100
2022-09-09 21:41:41,523 - GivTCP_Write_1 - [ERROR] - Setting Charge Target failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x00000198657A1080>)
2022-09-09 21:41:41,987 - GivTCP_Write_1 - [ERROR] - Setting Charge Slot 1 failed: (<class 'AssertionError'>, AssertionError('Unexpected response from remote end: Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response'), <traceback object at 0x00000198657BBA00>)
